# Generated by Django 4.2.1 on 2023-06-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChangAnNight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='collects',
            field=models.ManyToManyField(blank=True, to='ChangAnNight.articles', verbose_name='收藏的章节'),
        ),
    ]
